[tool.poetry]
name = "book-review"
version = "0.1.0"
description = "book review"
authors = ["jshuckbot <gorka_ivan@mail.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2"
pillow = "^10.1.0"
djangorestframework = "^3.15.2"
django-configurations = "^2.5.1"
dj-database-url = "^2.3.0"
django-crispy-forms = "^2.3"
crispy-bootstrap4 = "^2024.10"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^23.12.1"
autoflake = "^2.2.1"
xlsxwriter = "^3.2.0"
weasyprint = "^62.3"
plotly = "^5.23.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
