# Generated by Django 4.2 on 2024-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviewsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="sample",
            field=models.FileField(blank=True, null=True, upload_to="boot_samples/"),
        ),
    ]
